name: SuperJump
author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
main: com.spleefleague.superjump.SuperJump
version: 1.0
depend: [SpleefLeagueCore]
commands:    
    superjump:
        description: SuperJump queue command
        aliases: [sj]
        usage: |
          /<command> [arena]